version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - run:
          name: Install Lektor
          command: |
            sudo pip install Lektor
            lektor build && lektor deploy ghpages
