version: 1.0

jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/
    steps:
      - run:
          name: Install Lektor
          command: |
            pip install Lektor
            lektor build
            lektor deploy ghpages
